name: Publish

on: [push]

jobs:
  main:
    name: Publish
    runs-on: ubuntu-latest
    concurrency: publish-${{ github.ref }}

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: linz/action-typescript@dee99184c4305aea6c380a52db9b2d7abaaa3e78 # v3

      # FIXME: catalog.json is not pushed to the repository (temporary solution)
      # - name: Create STAC Catalog
      #   uses: docker://ghcr.io/linz/argo-tasks:v2
      #   with:
      #     args: stac-catalog --output stac/catalog.json --template template/catalog.json /github/workspace/stac/

      # - name: Validate STAC Catalog
      #   uses: docker://ghcr.io/linz/argo-tasks:v2
      #   with:
      #     args: stac-validate /github/workspace/stac/catalog.json

      - name: Validate STAC Collections
        run: |
          # Enable double star operator
          shopt -s globstar
          docker run -v $PWD:$PWD ghcr.io/linz/argo-tasks:v2 stac-validate $PWD/stac/**/collection.json

      - name: AWS Configure
        if: github.ref == 'refs/heads/master'
        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355 # v2
        with:
          aws-region: ap-southeast-2
          mask-aws-account-id: true
          role-to-assume: ${{ secrets.AWS_CI_ROLE }}

      # Sync STAC files only on push to 'master'
      # - name: Sync STAC
      #   uses: docker://ghcr.io/linz/argo-tasks:v2
      #   if: github.ref == 'refs/heads/master'
      #   with:
      #     args: stac-sync /github/workspace/stac/ s3://linz-elevation/
